# ===== mkdocs.yml =====
# Configuration file for the automatic generation of package
# documentation formatted with markdown.

# ===== Setup and Themes =====
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

site_name: sibylla - gradient descent image reconstruction
repo_url: https://github.com/benjaminpope/sibylla

theme:
  name: material
  icon:
    logo: material/telescope

# ===== Plugins =====
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          setup_commands:
            - import sys
            - sys.path.append("dLux")
          rendering:
            show_source: false
            show_if_no_docstring: yes
      custom_templates: templates

# ===== Navigation =====
nav:
    - Home: index.md
